# Generated by Django 5.0.1 on 2024-03-22 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='core/images')),
                ('link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
                ('about', models.TextField(null=True)),
                ('image', models.ImageField(default='', upload_to='core/images')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='affiliatestore.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(default='', max_length=50)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(default='')),
                ('image', models.ImageField(default='', upload_to='core/images')),
                ('storename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliatestore.stores')),
            ],
        ),
    ]
